// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgkMX8iLSya3KU7J841yVKK2XWNxqtukQ',
    appId: '1:333425590968:web:15ea1699ffdfbc388fea4d',
    messagingSenderId: '333425590968',
    projectId: 'proyectofinal-7a615',
    authDomain: 'proyectofinal-7a615.firebaseapp.com',
    storageBucket: 'proyectofinal-7a615.appspot.com',
    measurementId: 'G-9R6PJEJEFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKUN_AEaVeCnddQmFgPS76NR2RlXbaRu0',
    appId: '1:333425590968:android:3d5b8cf5012aab478fea4d',
    messagingSenderId: '333425590968',
    projectId: 'proyectofinal-7a615',
    storageBucket: 'proyectofinal-7a615.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-KbY4MVAckdYV6KnJxWfo9Qn0f64zSsY',
    appId: '1:333425590968:ios:48d2534e7f5ef5248fea4d',
    messagingSenderId: '333425590968',
    projectId: 'proyectofinal-7a615',
    storageBucket: 'proyectofinal-7a615.appspot.com',
    iosClientId: '333425590968-ojfjeted4lk34q3s39jbt50rj7rqshd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoFinal',
  );
}
